/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package StartGUI;

import java.sql.*;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Prateek Jhunjhunwala
 */
public class EnterPurchase extends javax.swing.JFrame {

    /**
     * Creates new form EnterPurchase
     */
    public EnterPurchase() {
        initComponents();
        lb1.setVisible(false);
        tf1.setVisible(false);
        lb2.setVisible(false);
        cb.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta1 = new javax.swing.JTable();
        lb2 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tf1 = new javax.swing.JTextField();
        tf2 = new javax.swing.JTextField();
        tf4 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        tf3 = new javax.swing.JTextField();
        confirmpurchase = new javax.swing.JButton();
        deleterow = new javax.swing.JButton();
        printorder = new javax.swing.JButton();
        lb1 = new javax.swing.JLabel();
        cb = new javax.swing.JComboBox();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        addrow1 = new javax.swing.JButton();
        addrow2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jta1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "S.No", "Ingredient Name", "Quantity", "Rate", "Amount"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jta1.setColumnSelectionAllowed(true);
        jScrollPane1.setViewportView(jta1);
        jta1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jta1.getColumnModel().getColumnCount() > 0) {
            jta1.getColumnModel().getColumn(0).setResizable(false);
            jta1.getColumnModel().getColumn(1).setResizable(false);
            jta1.getColumnModel().getColumn(2).setResizable(false);
            jta1.getColumnModel().getColumn(3).setResizable(false);
            jta1.getColumnModel().getColumn(4).setResizable(false);
        }

        lb2.setText("Enter a New Ingredient Name:");

        jLabel2.setText("Enter Rate:");

        jLabel3.setText("Quantity:");

        tf4.setText("0.0");

        jLabel4.setText("Total Puchase Amount:");

        confirmpurchase.setText("Confirm Purchase Order");
        confirmpurchase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmpurchaseActionPerformed(evt);
            }
        });

        deleterow.setText("Delete Selected Row");
        deleterow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleterowActionPerformed(evt);
            }
        });

        printorder.setText("Print Purchase Order");
        printorder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printorderActionPerformed(evt);
            }
        });

        lb1.setText("Select an Ingredient from existing list:");

        buttonGroup1.add(rb1);
        rb1.setText("Select an Ingredient from the existing list");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(rb2);
        rb2.setText("Add a New Ingredient to the list");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });

        addrow1.setText("GO BACK");
        addrow1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrow1ActionPerformed(evt);
            }
        });

        addrow2.setText("Add the Ingredient");
        addrow2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addrow2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb1)
                        .addGap(18, 18, 18)
                        .addComponent(rb2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lb2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lb1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tf1, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(tf2, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(tf3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(tf4, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                            .addComponent(cb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(confirmpurchase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(deleterow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addrow1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addrow2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(printorder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {confirmpurchase, deleterow, printorder});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rb1)
                    .addComponent(rb2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lb1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cb, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(printorder, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lb2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tf1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(addrow2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleterow, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmpurchase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tf4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(addrow1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printorderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printorderActionPerformed
        MessageFormat header =new MessageFormat("Menu Card");
        java.util.Date dat=new java.util.Date();
        MessageFormat footer =new MessageFormat(dat.toString()); 
        try
        {
            jta1.print(JTable.PrintMode.NORMAL, header, footer);
        }
        catch(java.awt.print.PrinterException e)
        {
            System.err.format("cannot print %s%b",e.getMessage());
        }
    }//GEN-LAST:event_printorderActionPerformed

    private void confirmpurchaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmpurchaseActionPerformed
        int choice=JOptionPane.showConfirmDialog(null, "Are you sure you want to confirm the order?");
        if(choice==0)
        {
                try
                {
                    Class.forName("java.sql.Driver");
                    Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/restaurant","root","prateek");
                    Statement s1=con.createStatement();
                    ResultSet rs1=s1.executeQuery("Select count(*) from ingredients");
                    int nextbillno=0;
                    while(rs1.next())
                    {
                        nextbillno=rs1.getInt(1)+1;
                    }
                    MessageFormat header =new MessageFormat("Bill No.: "+nextbillno);
                    java.util.Date dat=new java.util.Date();
                    MessageFormat footer =new MessageFormat(dat.toString());
                    try
                    {
                        jta1.print(JTable.PrintMode.NORMAL, header, footer);
                    }
                    catch(java.awt.print.PrinterException e)
                    {
                        System.err.format("cannot print %s%b",e.getMessage());
                    }
                    for(int i=0;i<jta1.getRowCount();i++)   
                    {                    
                        int z2=0;                    
                        Object temp=jta1.getModel().getValueAt(i,2);
                        int temp1=Integer.parseInt(temp+"");
                        String itemname=jta1.getModel().getValueAt(i,1)+"";
                        Double pr=Double.parseDouble(jta1.getModel().getValueAt(i,3)+"");
                        s1.executeUpdate("Insert into ingredients (BillNo,Item,Quantity,Price) values ("+nextbillno+",'"+itemname+"',"+temp1+","+pr+");");
                        rs1=s1.executeQuery("Select * from ingredientquantity where Item='"+itemname+"';");
                        if(rs1.next())
                        {
                            int z=rs1.getInt("Quantity");
                            int x=z+temp1;
                            s1.executeUpdate("Update ingredientquantity set Quantity="+x+"where Item='"+itemname+"';");
                        }
                        else
                        {
                            s1.executeUpdate("Insert into ingredientquantity values ('"+itemname+"',"+temp1+");");
                        }
                    }
                    dispose();
                    new Clerk().setVisible(true);
                }
                catch(ClassNotFoundException ex)
                {
                    Logger.getLogger(EnterPurchase.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                Logger.getLogger(EnterPurchase.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_confirmpurchaseActionPerformed

    private void deleterowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleterowActionPerformed
        if(jta1.getSelectedRow()==-1)
        {
            JOptionPane.showMessageDialog(null,"Please select a row to delete it");
        }
        else
        {
            int choice=JOptionPane.showConfirmDialog(null,"Are you sure you want to remove the selected row?");
            if(choice==0)
            {
                Object temp=jta1.getModel().getValueAt(jta1.getSelectedRow(),4);
                DefaultTableModel model=(DefaultTableModel) jta1.getModel();
                model.removeRow(jta1.getSelectedRow());
                for(int i=0;i<jta1.getRowCount();i++)
                {
                    jta1.setValueAt(i+1, i, 0);
                }
                tf4.setText(Double.parseDouble(tf4.getText()+"")-Double.parseDouble(temp+"")+"");
            }
        }
    }//GEN-LAST:event_deleterowActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        if(rb1.isSelected())
        {
            lb1.setVisible(true);
            cb.setVisible(true);
            lb2.setVisible(false);
            tf1.setVisible(false);
        }
        else
        {
            lb2.setVisible(true);
            tf1.setVisible(true);
            lb1.setVisible(false);
            cb.setVisible(false);
        }
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        if(rb1.isSelected())
        {
            lb1.setVisible(true);
            cb.setVisible(true);
            lb2.setVisible(false);
            tf1.setVisible(false);
        }
        else
        {
            lb2.setVisible(true);
            tf1.setVisible(true);
            lb1.setVisible(false);
            cb.setVisible(false);
        }
    }//GEN-LAST:event_rb2ActionPerformed

    private void addrow1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrow1ActionPerformed
        new Clerk().setVisible(true);
        dispose();
    }//GEN-LAST:event_addrow1ActionPerformed

    private void addrow2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addrow2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addrow2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnterPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnterPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnterPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnterPurchase.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EnterPurchase().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addrow1;
    private javax.swing.JButton addrow2;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox cb;
    private javax.swing.JButton confirmpurchase;
    private javax.swing.JButton deleterow;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jta1;
    private javax.swing.JLabel lb1;
    private javax.swing.JLabel lb2;
    private javax.swing.JButton printorder;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JTextField tf1;
    private javax.swing.JTextField tf2;
    private javax.swing.JTextField tf3;
    private javax.swing.JTextField tf4;
    // End of variables declaration//GEN-END:variables
}
